---
apiVersion: v1
kind: Secret
metadata:
  name: penpot-frontend-secrets
type: Opaque
stringData:
  PENPOT_BACKEND_URI: "https://${PENPOT_DOMAIN}"
  PENPOT_EXPORTER_URI: "https://${PENPOT_DOMAIN}/api/export"
---
apiVersion: v1
kind: Secret
metadata:
  name: penpot-common-secrets
type: Opaque
stringData:
  PENPOT_FLAGS: "enable-registration enable-email-whitelist enable-login-with-password enable-smtp enable-prepl-server log-emails smtp-debug"
  PENPOT_REGISTRATION_DOMAIN_WHITELIST: "${PENPOT_REGISTRATION_DOMAIN_WHITELIST}"
  PENPOT_PUBLIC_URI: "https://${PENPOT_DOMAIN}"
  # I don't like to let services report back and expose potential infrastructure details, sorry...
  PENPOT_TELEMETRY_ENABLED: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: penpot-backend-secrets
type: Opaque
stringData:
  PENPOT_FLAGS: "enable-registration enable-email-whitelist enable-login-with-password enable-smtp enable-prepl-server log-emails smtp-debug"
  # use a good secret for the following, use:
  # python3 -c "import secrets; print(secrets.token_urlsafe(64))"
  PENPOT_SECRET_KEY: "<REPLACE ME>"
  PENPOT_PUBLIC_URI: "https://${PENPOT_DOMAIN}"
  PENPOT_DATABASE_URI: "postgresql://penpot-postgres/penpot"
  PENPOT_DATABASE_USERNAME: "penpot"
  # use a good database password, use to generate one:
  # python3 -c "import secrets; print(secrets.token_urlsafe(64))"  PENPOT_DATABASE_PASSWORD: "penpot"
  PENPOT_DATABASE_PASSWORD: "<REPLACE ME>"
  PENPOT_REDIS_URI: "redis://penpot-redis/0"
  PENPOT_TELEMETRY_ENABLED: "false"
  PENPOT_SMTP_DEFAULT_FROM: "penpot@example.com"
  PENPOT_SMTP_DEFAULT_REPLY_TO: "penpot@example.com"
  PENPOT_SMTP_HOST: "<REPLACE WITH YOUR SMTP HOST>"
  PENPOT_SMTP_USERNAME: "<REPLACE WITH YOUR SMTP SMARTHOST USERNAME>"
  PENPOT_SMTP_PASSWORD: "<REPLACE WITH YOUR SMTP SMARTHOST PASSWORD>"
  # I'm still using 465 over 587, please adjust to your needs accordingly for SSL/TLS
  PENPOT_SMTP_PORT: "465"
  PENPOT_SMTP_SSL: "true"
  PENPOT_SMTP_TLS: "true"
  PENPOT_ASSETS_STORAGE_BACKEND: "assets-s3"
  PENPOT_STORAGE_ASSETS_S3_ENDPOINT: "<REPLACE ME, e.g. https://minio-s3.example.com"
  PENPOT_STORAGE_ASSETS_S3_REGION: "<REPLACE WITH YOUR MINIO REGION>"
  PENPOT_STORAGE_ASSETS_S3_BUCKET: "<REPLACE WITH YOUR BUCKET NAME>"
  AWS_ACCESS_KEY_ID: "<REPLACE WITH YOUR MINIO ACCESS KEY>"
  AWS_SECRET_ACCESS_KEY: "<REPLACE WITH YOUR MINIO SECRET KEY>"
